# Utilise l'image officielle Node.js
FROM node:latest

# Crée et définit le répertoire de travail
WORKDIR /app

# Copie le fichier package.json et package-lock.json
COPY package*.json ./

# Installe les dépendances
RUN npm install

# Copie le reste des fichiers du projet
COPY . .

# Expose le port que Vite utilisera
EXPOSE 5173 5174

# Commande pour démarrer Vite
CMD ["npm", "run", "dev"]
