# Dockerfile.frontend
FROM node:latest

WORKDIR /app

# Copiez les fichiers de dépendance d'abord
COPY package.json package-lock.json ./

# Installez les dépendances
RUN npm install


# Copiez le reste du code
COPY . .


EXPOSE 5173 5174

CMD ["npm", "run", "dev"]
